# Dependencies
markdown: kramdown
highlighter: rouge

kramdown:
  auto_ids: true

permalink: pretty
source: docs
baseurl: ""

sass:
  sass_dir: ../
  style: compressed

github:
  repo: https://github.com/primer/primer
