markdown: kramdown
highlighter: rouge

kramdown:
  auto_ids: true

permalink: pretty
source: docs
baseurl: ""

version: 2.3.3

sass:
  sass_dir: ../
  style: compressed

github:
  repo: https://github.com/fac/origin
