name: Deploy
on:
  pull_request:

permissions:
  contents: write
  pages: write
  id-token: write
  deployments: write
  issues: write
  statuses: write
  checks: write

jobs:
  deploy:
    if: ${{ github.repository == 'primer/css' }}
    uses: primer/.github/.github/workflows/deploy_preview.yml@main
    name: Deploy preview
    with:
      node_version: 14
      install: yarn && cd docs && yarn && cd ..
      build: yarn build:docs:preview
      output_dir: docs/public

  deploy-storybook:
    if: ${{ github.repository == 'primer/css' }}
    name: Preview Storybook
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@v3

      - uses: chrnorm/deployment-action@v2.0.3
        name: Create GitHub deployment for storybook
        id: storybook
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: Storybook Preview
          environment_url: '${{ needs.deploy.outputs.deployment_url }}/storybook'

      - name: Update storybook deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment-url: '${{ needs.deploy.outputs.deployment_url }}/storybook'
          state: 'success'
          deployment-id: ${{ steps.storybook.outputs.deployment_id }}

      - name: Update storybook deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          state: 'failure'
          deployment-id: ${{ steps.storybook.outputs.deployment_id }}
