name: Release
on:
  push:
    branches-ignore:
      - 'main'
      - 'changeset-release/**'
    # Don't release canary when these paths change
    # It's not necessary because we don't ship them and it creates noise
    paths-ignore:
      - '.changeset/**'
      - 'docs/**'
      - 'lib/**'
      - '__tests__/**'
      - 'script/**'
      - 'next.config.js'
      - 'now.json'

jobs:
  release-canary:
    name: Canary
    uses: primer/.github/.github/workflows/release_canary.yml@v2.1.1
    with:
      install: npm ci
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      npm_token: ${{ secrets.NPM_AUTH_TOKEN_SHARED }}
